# docker compose -p "alpine-bind9-doh" up -d
services:
  bind9:
    container_name: bind9-dns
    image: alpine-bind9:1
    restart: unless-stopped
    build: 
      context: .
      dockerfile: dockerfile
    volumes:
      - dns_config:/etc/bind
    expose:
      - 8888
  nginx:
    container_name: bind9-reverse-proxy
    restart: unless-stopped
    volumes: 
      - ./Config/Nginx/certs:/etc/nginx/certs
      - ./Config/Nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 443:443
    image: nginx:1.27.1
volumes:
  dns_config: